version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 3000:8080
    volumes:
      - ./app/:/app/
    command: npm run dev
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
