version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    image: plsn/example-app
    depends_on: 
      - db
  db:
    image: postgres
    env_file:
       .env
