version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    image: plsn/example-app
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
